export const PRODUCT_CATEGORIES = [
  {
    name: 'Electronics',
    type: [
      { name: 'Cellphone', max_price: 1800, min_price: 150 },
      { name: 'TV', max_price: 5000, min_price: 250 },
      // { name: 'Computers', max_price: 4000, min_price: 400 },
      // { name: 'Laptops', max_price: 3500, min_price: 300 },
      // { name: 'Tablets', max_price: 1200, min_price: 100 },
      // { name: 'Smartwatches', max_price: 900, min_price: 50 },
      // { name: 'Headphones', max_price: 600, min_price: 20 },
      // { name: 'Cameras', max_price: 6000, min_price: 400 },
      // { name: 'Speakers', max_price: 1500, min_price: 30 },
      // { name: 'Gaming Consoles', max_price: 700, min_price: 250 },
    ],
  },
  // {
  //   name: 'Clothing',
  //   type: [
  //     { name: 'Sweaters', max_price: 450, min_price: 30 },
  //     { name: 'Pants', max_price: 300, min_price: 25 },
  //     { name: 'Shoes', max_price: 1200, min_price: 40 },
  //     { name: 'Jackets', max_price: 1500, min_price: 60 },
  //     { name: 'T-Shirts', max_price: 150, min_price: 15 },
  //     { name: 'Dresses', max_price: 2000, min_price: 40 },
  //     { name: 'Shorts', max_price: 120, min_price: 20 },
  //     { name: 'Socks', max_price: 40, min_price: 5 },
  //     { name: 'Underwear', max_price: 80, min_price: 10 },
  //   ],
  // },
  // {
  //   name: 'Kitchenware',
  //   type: [
  //     { name: 'Silverware', max_price: 600, min_price: 40 },
  //     { name: 'Appliances', max_price: 2500, min_price: 80 },
  //     { name: 'Storage containers', max_price: 150, min_price: 20 },
  //     { name: 'Cookware Sets', max_price: 1200, min_price: 100 },
  //     { name: 'Bakeware', max_price: 300, min_price: 15 },
  //     { name: 'Knives', max_price: 800, min_price: 30 },
  //     { name: 'Coffee Makers', max_price: 1500, min_price: 40 },
  //     { name: 'Blenders', max_price: 600, min_price: 30 },
  //     { name: 'Toasters', max_price: 200, min_price: 25 },
  //   ],
  // },
  // {
  //   name: 'Furniture',
  //   type: [
  //     { name: 'Sofas', max_price: 8000, min_price: 500 },
  //     { name: 'Dining Tables', max_price: 4500, min_price: 200 },
  //     { name: 'Office Chairs', max_price: 1800, min_price: 100 },
  //     { name: 'Beds', max_price: 6000, min_price: 300 },
  //     { name: 'Bookshelves', max_price: 1200, min_price: 80 },
  //     { name: 'Coffee Tables', max_price: 900, min_price: 70 },
  //     { name: 'Nightstands', max_price: 500, min_price: 40 },
  //     { name: 'Wardrobes', max_price: 3000, min_price: 200 },
  //   ],
  // },
  // {
  //   name: 'Automotive',
  //   type: [
  //     { name: 'Tires', max_price: 500, min_price: 80 },
  //     { name: 'Dash Cams', max_price: 600, min_price: 50 },
  //     { name: 'Car Audio', max_price: 2000, min_price: 150 },
  //     { name: 'GPS Units', max_price: 400, min_price: 80 },
  //     { name: 'Floor Mats', max_price: 250, min_price: 30 },
  //     { name: 'Car Covers', max_price: 300, min_price: 50 },
  //     { name: 'Seat Covers', max_price: 400, min_price: 40 },
  //     { name: 'Wiper Blades', max_price: 60, min_price: 15 },
  //   ],
  // },
  // {
  //   name: 'Beauty',
  //   type: [
  //     { name: 'Skincare', max_price: 400, min_price: 10 },
  //     { name: 'Makeup', max_price: 250, min_price: 5 },
  //     { name: 'Fragrance', max_price: 600, min_price: 40 },
  //     { name: 'Hair Care', max_price: 300, min_price: 8 },
  //     { name: 'Nail Care', max_price: 150, min_price: 5 },
  //     { name: "Men's Grooming", max_price: 200, min_price: 15 },
  //     { name: 'Tools and Brushes', max_price: 400, min_price: 10 },
  //     { name: 'Bath and Body', max_price: 100, min_price: 5 },
  //   ],
  // },
  // {
  //   name: 'Sports and Outdoors',
  //   type: [
  //     { name: 'Bicycles', max_price: 1800, min_price: 200 },
  //     { name: 'Tents', max_price: 1200, min_price: 50 },
  //     { name: 'Fitness Trackers', max_price: 600, min_price: 30 },
  //     { name: 'Dumbbells', max_price: 500, min_price: 20 },
  //     { name: 'Yoga Mats', max_price: 150, min_price: 15 },
  //     { name: 'Sleeping Bags', max_price: 400, min_price: 30 },
  //     { name: 'Fishing Rods', max_price: 800, min_price: 40 },
  //     { name: 'Backpacks', max_price: 450, min_price: 30 },
  //   ],
  // },
  // {
  //   name: 'Toys and Games',
  //   type: [
  //     { name: 'Action Figures', max_price: 200, min_price: 10 },
  //     { name: 'Board Games', max_price: 150, min_price: 15 },
  //     { name: 'Puzzles', max_price: 80, min_price: 10 },
  //     { name: 'Dolls', max_price: 300, min_price: 15 },
  //     { name: 'LEGO Sets', max_price: 900, min_price: 20 },
  //     { name: 'Remote Control Cars', max_price: 500, min_price: 30 },
  //     { name: 'Educational Toys', max_price: 250, min_price: 20 },
  //     { name: 'Card Games', max_price: 100, min_price: 10 },
  //   ],
  // },
  // {
  //   name: 'Home Improvement',
  //   type: [
  //     { name: 'Power Drills', max_price: 400, min_price: 40 },
  //     { name: 'Smart Lighting', max_price: 300, min_price: 20 },
  //     { name: 'Generators', max_price: 3000, min_price: 400 },
  //     { name: 'Hand Tools', max_price: 500, min_price: 10 },
  //     { name: 'Lawn Mowers', max_price: 2500, min_price: 200 },
  //     { name: 'Paint', max_price: 100, min_price: 30 },
  //     { name: 'Thermostats', max_price: 350, min_price: 50 },
  //     { name: 'Security Cameras', max_price: 1200, min_price: 40 },
  //   ],
  // },
  // {
  //   name: 'Musical Instruments',
  //   type: [
  //     { name: 'Guitars', max_price: 5000, min_price: 150 },
  //     { name: 'Digital Pianos', max_price: 4000, min_price: 300 },
  //     { name: 'Drums', max_price: 3500, min_price: 400 },
  //     { name: 'Microphones', max_price: 1200, min_price: 50 },
  //     { name: 'Keyboards', max_price: 2500, min_price: 100 },
  //     { name: 'Violins', max_price: 6000, min_price: 200 },
  //     { name: 'Saxophones', max_price: 5000, min_price: 400 },
  //     { name: 'Amps', max_price: 2000, min_price: 100 },
  //   ],
  // },
  // {
  //   name: 'Pet Supplies',
  //   type: [
  //     { name: 'Pet Food', max_price: 120, min_price: 20 },
  //     { name: 'Aquariums', max_price: 2000, min_price: 50 },
  //     { name: 'Grooming Tools', max_price: 150, min_price: 15 },
  //     { name: 'Dog Crates', max_price: 300, min_price: 40 },
  //     { name: 'Cat Trees', max_price: 400, min_price: 50 },
  //     { name: 'Leashes and Collars', max_price: 100, min_price: 10 },
  //     { name: 'Pet Beds', max_price: 250, min_price: 20 },
  //     { name: 'Bird Cages', max_price: 600, min_price: 40 },
  //   ],
  // },
  // {
  //   name: 'Books and Media',
  //   type: [
  //     { name: 'Hardcover Books', max_price: 100, min_price: 15 },
  //     { name: 'Vinyl Records', max_price: 250, min_price: 20 },
  //     { name: 'E-readers', max_price: 400, min_price: 90 },
  //     { name: 'Paperback Books', max_price: 40, min_price: 8 },
  //     { name: 'Textbooks', max_price: 350, min_price: 50 },
  //     { name: 'Magazines', max_price: 20, min_price: 5 },
  //     { name: 'Movies', max_price: 50, min_price: 10 },
  //     { name: 'Comics', max_price: 150, min_price: 5 },
  //   ],
  // },
];
